# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jump_cutoff <- function(pa_in, pb_in, xi_in, alpha_in) {
    .Call(`_JUMPrcpp_jump_cutoff`, pa_in, pb_in, xi_in, alpha_in)
}

